### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ASDLORD** [LorenK96/slide-desktop#1]
This project is sooo bad, it has a 100% chance on getting error for me. DeviceMessageType.java gives me this error in every fcknig compiler "cannot resolve symbol 'const'". Why upload a program if you cant even run it?

**Comment by lkuich** [comment]
Builds fine for me from a fresh pull. Make sure you've included the JAR's under the lib folder in your classpath, and have specified a Scala SDK. Const is a Singleton under the slide package. This is GitHub, you're expected to be a developer when cloning and building from source.
If you're looking for a download link:
http://www.slide-app.com/installation/
