### ISSUE TITLE
Java version on Mac

### ISSUE THREAD

**Issue by tophneal** [LorenK96/slide-desktop#6]
I just downloaded the DMG from the website, and hit an issue during installation.

After downloading the DMG and running install, I'm given a dialogue box to update my Java SE, in order to use the command-line tool "java." However, my SE is already on version 8u66 (as listed on the site.) When I open the Slide.app, I get a similar error that specifically states I need to install Java.

In both dialogue boxes, the buttons direct you to different URLs. "OK" takes you to http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html and "More Information" takes you to http://www.java.com/en/download/mac_download.jsp

I tried both, but it doesn't seem to matter, since according to Java, I'm already up-to-date.

I am running OS X 10.11.2

**Comment by lkuich** [comment]
OSX and Java don't play well nowadays, I had a TON of trouble with it.

Apple will always try to get you to install Java 6 for some reason (that's the dialog box you're seeing). You can run the app from the terminal directly:

`java -jar /path/to/jar/Slide.jar` (Substituting `path/to/jar` with the path to the Slide.jar file [located in Slide.app])

I'll make a guess and say your default JRE is incorrect:
- Open a terminal session and type: `java -version`
- It should say Java 1.8.X_XX, if not (and you've already installed Java 8), you need to set your default JRE to Java 1.8
- Here's some links to resources you can use to do this (this is a popular issue if you Google it):
  http://docs.oracle.com/javase/8/docs/technotes/guides/install/mac_jdk.html
  http://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-os-x
